### ISSUE TITLE
the mod is not working

### ISSUE THREAD

**Issue by blueman5** [nexor-source/InstantBuy#2]
i tried to buy a item on the terminal it have me this error: 

`[Info   : Unity Log] noun keyword: shovel ; verb keyword: buy ; result null? : False
[Info   : Unity Log] result: buyShovel
[Error  : Unity Log] FormatException: Input string was not in a correct format.
Stack trace:
System.Number.ThrowOverflowOrFormatException (System.Boolean overflow, System.String overflowResourceKey) (at <787acc3c9a4c471ba7d971300105af24>:0)
System.Number.ParseInt32 (System.ReadOnlySpan`1[T] value, System.Globalization.NumberStyles styles, System.Globalization.NumberFormatInfo info) (at <787acc3c9a4c471ba7d971300105af24>:0)
System.Int32.Parse (System.String s) (at <787acc3c9a4c471ba7d971300105af24>:0)
System.Linq.Enumerable+SelectArrayIterator`2[TSource,TResult].ToList () (at <dab7f68612224ba3ae40f651d44f9d4c>:0)
System.Linq.Enumerable.ToList[TSource] (System.Collections.Generic.IEnumerable`1[T] source) (at <dab7f68612224ba3ae40f651d44f9d4c>:0)
InstantBuy.InstantBuy+Terminal_Patch.Prefix (Terminal __instance, System.Int32 newGroupCredits, System.Int32& numItemsInShip) (at <fa312e26c10d47099979efc617165db5>:0)
(wrapper dynamic-method) Terminal.DMD<Terminal::SyncGroupCreditsClientRpc>(Terminal,int,int)
Terminal.LoadNewNodeIfAffordable (TerminalNode node) (at <255c0877f9414c3aa6f1fe5079ac13f3>:0)
Terminal.OnSubmit () (at <255c0877f9414c3aa6f1fe5079ac13f3>:0)
UnityEngine.Events.InvokableCall.Invoke () (at <e27997765c1848b09d8073e5d642717a>:0)
UnityEngine.Events.UnityEvent`1[T0].Invoke (T0 arg0) (at <e27997765c1848b09d8073e5d642717a>:0)
TMPro.TMP_InputField.SendOnEndEdit () (at <9baa8119dbcd498f902c1a92f10843c1>:0)
TMPro.TMP_InputField.ReleaseSelection () (at <9baa8119dbcd498f902c1a92f10843c1>:0)
TMPro.TMP_InputField.DeactivateInputField (System.Boolean clearSelection) (at <9baa8119dbcd498f902c1a92f10843c1>:0)
TMPro.TMP_InputField.OnUpdateSelected (UnityEngine.EventSystems.BaseEventData eventData) (at <9baa8119dbcd498f902c1a92f10843c1>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IUpdateSelectedHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <17de86d66286445fa95af59fa8fa644d>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <17de86d66286445fa95af59fa8fa644d>:0)
UnityEngine.EventSystems.EventSystem:Update()`

**Comment by blueman5** [comment]
only the first version is working

**Comment by nexor-source** [comment]
This issue should have been fixed in v 0.0.4, thanks for your feedback!
