### ISSUE TITLE
I cant leave terminal when i buy something

### ISSUE THREAD

**Issue by andrzej2273** [nexor-source/InstantBuy#3]
Like in the title. Only v0.0.1 works fine and make no problems.
![image](https://github.com/nexor-source/InstantBuy/assets/168291598/05dc3615-86d6-457c-8daa-8a5a381890d8)

**Comment by nexor-source** [comment]
Well, I haven't encountered this problem myself, are you sure that version 0.0.1 doesnt have this problem while version 0.0.4 does?

**Comment by andrzej2273** [comment]
Hmm I'll run some tests later.  Maybe there is some mod conflict.

**Comment by andrzej2273** [comment]
Ok, i figured it out. There is some conflict with very important mod for me. I disabled GeneralImprowments by ShaosilGaming and it started working.

**Comment by andrzej2273** [comment]
And I have no problem with version 0.0.1. I played with my friends on this version and it worked.

**Comment by andrzej2273** [comment]
I did more tests and I know which option exactly breaks your mod. When i set custom value in startingmoneyperplayer (i use value 30 in my modpack) terminal starts showing credits, and when i buy something i cant leave.
![11111Bez tytułu](https://github.com/nexor-source/InstantBuy/assets/168291598/281ef26f-d95a-4c2a-a3a7-937f7b1ad109)
![Bez tytułuins](https://github.com/nexor-source/InstantBuy/assets/168291598/803b8cab-8df2-4e49-a3fb-adeb8987bf42)

**Comment by andrzej2273** [comment]
and it's happening on new saves

**Comment by nexor-source** [comment]
I've fixed this stupid bug in version 0.0.5, thanks a lot for your feedback!

**Comment by andrzej2273** [comment]
Everything works now. Thanks a lot.
